---
title: "Covid-19 Data Visualizations"
---

```{r}
library(ggplot2)
library(hrbrthemes)
```

```{r}
fileUrl <- "https://data.chhs.ca.gov/dataset/f333528b-4d38-4814-bebb-12db1f10f535/resource/046cdd2b-31e5-4d34-9ed3-b48cdbc4be7a/download/covid19cases_test.csv"
covidData <- read.csv(fileUrl, header=TRUE, sep=",")
write.csv(covidData,"ca_timeseries_data.csv", row.names=FALSE)
```

```{r}
head(covidData)
```

```{r}
counties <- covidData$area
counties <- unique(counties)
counties <- as.vector(counties)
counties <- sort(counties)
counties <- counties[counties!=""]
```

```{r}
write_png <- function(file_name, data) {
  outputFile = sprintf("%s.png", file_name)
  ggsave(outputFile,dpi=1200)
  return()
}

write_jpg <- function(file_name, data) {
  outputFile = sprintf("%s.jpg", file_name)
  ggsave(outputFile,dpi=1200)
  return()
}

plot_graph <- function(data_set, x_axis_data, y_axis_data, title, x_label, y_label, file_name) {
  graph <- ggplot(data = data_set, aes_string(x = x_axis_data, y = y_axis_data)) +
      geom_line() + theme_ipsum() +
      labs(title = title,
           x = x_label, y = y_label)
  write_jpg(file_name = file_name, data = graph)
  write_png(file_name = file_name, data = graph)
}
```

```{r}
dir.create("visuals", showWarnings = FALSE)
setwd("visuals")

for(county in counties){
  if(county != "Out of state"){
    if(!dir.exists(county)){
      dir.create(county, showWarnings = FALSE)
    }
    setwd(county)
    
    currentCountyData <- covidData[covidData[, "area"] == county,] 
    currentCountyData$date <- as.Date(currentCountyData$date, format = "%Y-%m-%d")
    
    plot_graph(data_set = currentCountyData, x_axis_data = "date", y_axis_data = "cases", title = sprintf("Current Case Count of COVID-19 in %s County", county), x_label = "Month", y_label = "Current Case Count", file_name = "current_cases")
    
    
    print(county)
    setwd("..")
  }
}
```